-- =============================================================================
-- AI Interview Platform — database schema and row level security policies.
--
-- HONEST NOTE ON PROVENANCE: the table and column names below are the ones the
-- application actually queries (services/*, app/**, lib/server/*). The tables
-- were originally created through the Supabase dashboard, so this file is a
-- reconstruction rather than the original migration. Diff it against your own
-- project before trusting it, and treat it as the starting point for a fresh
-- project rather than as a record of an existing one.
--
-- Identifiers are quoted because the application uses mixed case names.
-- Run this in the Supabase SQL editor.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

create table if not exists public."Users" (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text,
  email       text not null unique,
  picture     text,
  credits     integer not null default 3
);

create table if not exists public."Interviews" (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  "jobPosition"   text not null,
  "jobDescription" text not null,
  duration        text not null,
  -- Written by the client as a JSON-encoded array of interview types, e.g.
  -- '["Technical","Behavioral"]'. Parsed defensively in InterviewDetailContainer.
  type            text,
  "questionList"  jsonb not null default '[]'::jsonb,
  -- The recruiter who owns this interview. Ownership is enforced on this column.
  "userEmail"     text not null,
  -- The unguessable id that appears in the shareable candidate link.
  interview_id    uuid not null unique
);

create table if not exists public."interview-feedback" (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  "userName"    text not null,
  "userEmail"   text,
  interview_id  uuid not null references public."Interviews"(interview_id) on delete cascade,
  -- The full report: { version, overall, perQuestion[], feedback{ rating, summary, ... } }
  feedback      jsonb not null,
  recommended   boolean not null default false
);

-- Fixed-window rate limit counters. Only the service role touches this table.
create table if not exists public.rate_limits (
  key           text primary key,
  window_start  timestamptz not null,
  count         integer not null default 0
);

create index if not exists interviews_user_email_idx
  on public."Interviews" ("userEmail");
create index if not exists interview_feedback_interview_id_idx
  on public."interview-feedback" (interview_id);

-- -----------------------------------------------------------------------------
-- Row level security
--
-- Postgres is the authority on who may read what. The application also filters
-- by the signed-in user, but that is defence in depth: with RLS on, a client
-- holding the anon key cannot read another recruiter's interviews even if a
-- query forgets its filter.
--
-- The service role key bypasses RLS, which is why the candidate-facing routes
-- (app/api/interview/[interview_id], app/api/ai-feedback) run server-side —
-- an anonymous candidate is given exactly the one interview their link names
-- and never a key that can read the table.
-- -----------------------------------------------------------------------------

alter table public."Users"              enable row level security;
alter table public."Interviews"         enable row level security;
alter table public."interview-feedback" enable row level security;
alter table public.rate_limits          enable row level security;

-- Users: a signed-in user may only see and edit their own profile row.
drop policy if exists "users read own profile" on public."Users";
create policy "users read own profile" on public."Users"
  for select to authenticated
  using (email = auth.jwt() ->> 'email');

drop policy if exists "users create own profile" on public."Users";
create policy "users create own profile" on public."Users"
  for insert to authenticated
  with check (email = auth.jwt() ->> 'email');

drop policy if exists "users update own profile" on public."Users";
create policy "users update own profile" on public."Users"
  for update to authenticated
  using (email = auth.jwt() ->> 'email')
  with check (email = auth.jwt() ->> 'email');

-- Interviews: owned by the recruiter who created them. There is deliberately
-- no policy for the anon role, so an anonymous client cannot list interviews.
drop policy if exists "recruiters read own interviews" on public."Interviews";
create policy "recruiters read own interviews" on public."Interviews"
  for select to authenticated
  using ("userEmail" = auth.jwt() ->> 'email');

drop policy if exists "recruiters create own interviews" on public."Interviews";
create policy "recruiters create own interviews" on public."Interviews"
  for insert to authenticated
  with check ("userEmail" = auth.jwt() ->> 'email');

drop policy if exists "recruiters update own interviews" on public."Interviews";
create policy "recruiters update own interviews" on public."Interviews"
  for update to authenticated
  using ("userEmail" = auth.jwt() ->> 'email')
  with check ("userEmail" = auth.jwt() ->> 'email');

drop policy if exists "recruiters delete own interviews" on public."Interviews";
create policy "recruiters delete own interviews" on public."Interviews"
  for delete to authenticated
  using ("userEmail" = auth.jwt() ->> 'email');

-- Feedback: readable only by the recruiter who owns the parent interview.
-- Inserts are not granted to any client role; completed interviews are written
-- by the server (lib/server/interviews.js) using the service role key.
drop policy if exists "recruiters read feedback for own interviews" on public."interview-feedback";
create policy "recruiters read feedback for own interviews" on public."interview-feedback"
  for select to authenticated
  using (
    exists (
      select 1
      from public."Interviews" i
      where i.interview_id = public."interview-feedback".interview_id
        and i."userEmail" = auth.jwt() ->> 'email'
    )
  );

-- rate_limits: RLS is enabled with no policies, so anon and authenticated
-- clients have no access at all. A user must not be able to clear their own
-- counter, which is exactly why the server writes it with the service role key.
