/**
 * The shapes the application will accept back from a language model.
 *
 * Nothing generated by a model reaches the database or the UI without passing
 * one of these schemas first, so a malformed or hallucinated reply fails at the
 * boundary instead of rendering as NaN or being stored as junk.
 */
import { z } from "zod";

export const questionSchema = z.object({
  question: z.string().min(1),
  type: z.string().min(1),
});

export const questionListSchema = z.object({
  interviewQuestions: z.array(questionSchema).min(1).max(30),
});

/**
 * One scored answer. `score` is the only number the model is trusted with;
 * every aggregate figure shown in the UI is arithmetic over these (lib/score.js).
 */
export const answerScoreSchema = z.object({
  score: z.number().min(0).max(10),
  strengths: z.array(z.string().min(1)).max(5).default([]),
  gaps: z.array(z.string().min(1)).max(5).default([]),
  suggestedImprovement: z.string().min(1),
});

export const summarySchema = z.object({
  summary: z.string().min(1),
  recommendation: z.enum(["Yes", "No", "Maybe"]),
  recommendationMsg: z.string().min(1),
});
